-- Timeline

-- events
INSERT INTO events(event_name, event_desc, timeline_date) VALUES
('Prehistoric wars', 'False History: The Insectoid El-Koth rule the land of Hazlan, their great civilization is over run by the barbaric Duruun. The Duruun are then driven off by the Quelshar. This fey race is then destroyed in a war with Yath. Finally the Yath are destroyed by the Vossath Nor.The Insectoid El-Koth rule the land of Hazlan, their great civilization is over run by the barbaric Duruun. The Duruun are then driven off by the Quelshar. This fey race is then destroyed in a war with Yath. Finally the Yath are destroyed by the Vossath Nor.', -100344),
('Blars highland invastion', 'Forfar: The highland people are invaded by the Blars, they are driven out when Caral FirFair unites the clans. Caral himself leads the highlanders in the Battle of Deargleitir and slays the leader of the Blars. The clans all agree to stay united while they recover their losses, and all agree that Caral should be their king. This leads to the foundation of the Kingdom of FirFair. This is also the start of the Forfar Calendar (0 FC).', -1387),
('FirFair conquered', 'Forfar: The Kingdom of FirFair is conquered by the Merionites. They corrupt the name of FirFair to Forfar (792 FC).', -595),
('Forfar independence', 'Forfar: The Forfarians rise up and win their independence from the Merionites who had conquered them (952 FC).', -435),
('Nameless founding', 'Speculation - False History: The Nameless King leads the Mulan and their Rashemani slaves into the land of Hazlan, and conquer the Vossath Nor, the last of the nonhuman civilizations. He founds the Nameless Dynasty.', -344),
('Jander''s birth', 'Speculation - Toril: Jander Sunstar born on the isle of Evermeet. (394 DR) ', -225),
('Merrydale to Daggerdale', 'Speculation - Toril: Merrydale becomes Daggerdale during a vampiric infestation. (494 DR) ', -125),
('2nd Hazlani Dynasty', 'False History: The Nameless King peacefully passes his rule to the Dannouth family founding the Second Hazlani Dynasty', -44),
('Jandar''s a vampire', 'Speculation - Toril: Jander Sunstar becomes a vampire. (594 DR)', -25),
('BC begins', 'Beginning of the Barovian Calendar.', 1),
('Barovia founded', 'Nation of Barovia forged of independent city-states by the von Zarovich family.', 1),
('Borjia-Barovia alliance', 'The founding of Barovia also united the City States to the west into the semi-independent region of Borjia. The wealthy mercantile families, Cosco, Boritsi, Olszanik and Dilisnya use their wealth to purchase titles in the new country of Barovia and in Borjia, strengthening the ties between the two regions to the extent where Borjia was seen as part of Barovia.', 1),
('First domain', 'Summer: The massacre at the Wedding of Sergei von Zarovich occurs. Barovia forms as the first Ravenloft domain due the actions of Strahd von Zarovich. Strahd turns into a vampire.', 351),
('Duncan MacFarn''s death', 'On the anniversary of their murder, Donal MacFarn and the Ghosts of Hospitality possess the stones of Castle Forfarmax and kill the traitor Duncan MacFarn and his retinue of servants and guests, leaving Castle Forfarmax empty and abandoned for centuries.', 351),
('Tatyana''s first reincarnation', 'First known reincarnation of Tatyana appears. Strahd meets a young woman named Marina when he purchases some spellbooks from her adoptive father, Burgomaster Lazlo, in the guise of Vasili Von Holtz.', 400),
('Azalin''s arrival', 'Azalin enters Ravenloft and arrives in Barovia.', 542),
('Birth of Vlad', 'Vlad Drakov is born on the outlander world of Krynn.', 665),
('Jander slays Cassiar','Speculation - Toril: Jander slays his master, Cassiar; he visits his old companion, Lyria “the Lovely” in Waterdeep in hopes of a cure. Jander learns there is no cure for undeath. (701 DR) ','82'),
('Istar''s Kingpriest','Speculation - Krynn: On the continent of Ansalon, Istar installs a Kingpriest. (280 PC)','86'),
('Fallen Myth','Speculation -  Toril: The fall of Myth Drannor. (714 DR: Year of Doom) ','95'),
('Kingpriest contruct','Speculation -  Krynn: Construction begins on the Temple of the Kingpriest (260 PC).','103'),
('Spellseer construct','Speculation -  Toril: Tregas Spellseer begins construction on Castle Spellseer in Amn, a few miles south of the Tethyr Road. (755 DR: Year of the Enigma).','136'),
('Kingpriest complete','Speculation -  Krynn: Temple of the Kingpriest completed (212 PC).','151'),
('First Shadows','In an unknown time centuries before this event, the sorcerer-fiend Gwydion, an alien being of horrific power from the Demiplane of Shadow, drew the ellefolk race into his realm to serve him. Pleased with his ellefolk slaves’ centuries of service, Gwydion infuses them with the essence of shadow, his “gift” transforming them from ellefolk to the “fey.” On the same day, twins are born to the fey’s leader, Arak the Erlking, and his wife Finngalla. These infants, Loht and his sister Maeve, are the first true shadow elves. Finngalla dies in childbirth.','151'),
('Rauxes Overking','Oerth: In the region called the Flaeness, the Overking is crowned in Rauxes; frontiers of Great Kingdom reach the City of Greyhawk. (CY 1; beginning of Common Years) ','152'),
('Unnamed Thorp','In a unnamed world the a small fishing thorp is founded in Arden Bay, the thorp will one day become Mordentshire.','157'),
('Daglan born','Daglan Daegon born in a “faraway land.” ','158'),
('Spellseer death','Speculation -  Toril: Tregas Spellseer dies. (783 DR)','164'),
('Zarovich blessing','The formal founding of the Barovian state Church of Andral, with the blessing of the Von Zarovich family.','168'),
('Spellseer complete','Speculation -  Toril: Construction of Castle Spellseer is completed. (795 DR: Year of the Firehawk).','176'),
('Renie hamlet','Jacques Renier brings his family here and takes leadership of the then hamlet of Mordentshire. He eventually builds Gryphon Manor. Within the year, Renier and his family flee the house, and Gryphon Manor’s reputation as an accursed place begins','180'),
('Kartak born','Speculation -  Toril: Kartak Spellseer born (802 DR).','183'),
('Flora born','Forfar: Flora ApBlanc is born to Lord Keegan ApBlanc and Lady Eileen ApBlanc (1573 FC).','186'),
('Gundar born','Gundar born in Prime Material Hunadora, which has just been conquered by the tyrant Otto III.','193'),
('Tristen kills Gilan','1825 Forfarian Calendar'': Tristen ApBlanc accidentally kills Gilan ApBlanc when he sends his wolves after the boy''s dog Petitcrieu.','439'),
('Strahd Diary','According to a version of Strahd''s diary ready by van Richten in 736 BC, Alina, the second reincarnation of Tatyana Federovna dies of fever in this year of 445 BC. Count Strahd attempts suicide with Alina in hand, but the Mists prevent him and snatch away her corpse. However, this goes against a version of Strahd''s diary read by Jander Sunstar that says Tatyana''s second reincarnation was Olya Ivanova who died 30 years later in 475 BC',445),
('Tristen kills Morholt','1833 Forfarian Calendar: Tristen ApBlanc mistakenly murders the sleeping Morholt ApBlanc, intending instead to murder his teacher Duncan ApDuguid.',446),
('First Dead Mans War','First Dead Man’s War waged by Falkovnia against Darkon.',700);






-- domains
INSERT INTO domains(domain_name, domain_desc, region) VALUES
('Arkandale','Arkandale was a domain in the southern Core formed by an adventurous natural werewolf by the name of Nathan Timothy. Son of the notable Mordentish werewolf Eowin Timothy, Nathan was always compelled to wander. On some level, he seemed to believe that he might escape the Demiplane of Dread through his wanderings. Being a natural werewolf and raised as a monster, he left a trail of murders in his wake. When there was nowhere left to explore, he entered the Mists. They obliged him with a domain of his own: Arkandale. The year was 708 BC.', 'The Southern Core'),
('Barovia', 'Barovia is the first domain with which the Demiplane of Dread and the Core began, arising from the heinous actions Strahd von Zarovich in 351 BC. Strahd has continued to rule the land and the dour Barovian people through a fake line of successive rulers all bearing his name. In 740 BC, the Grand Conjunction dissolved the neighboring land of Gundarak and caused part of it to be absorbed by Barovia. Strahd''s political annexation of Gundarak has caused an ethnic strife that continues to inflame conflict between the ethnic Balok against the Gundarakites.', 'The Southern Core'),
('Bluetspur	', 'Back when Bluetspur was part of the core it was situated on the southeastern corner of the main continent, near the Balinok Mountains. Bluetspur''s landscape was a largely bleak and desolate stony wasteland, over which the sun never shines. Whenever "night" came the domain became intensely dark and small, glowing lights moved through the land. Following the domain''s degeneration into an island it began to be ravaged nightly by storms of such ferocity that survival on the surface was impossible. Any creatures who dared to spend the night on Bluetspur would be plagued by nightmares of horrific creatures slinking out from the rocks and devouring all life.', 'Island'),
('Borca', 'In 684 BR, the domain of Borca manifested into existence.', 'The Southern Core'),
('The Carnival', 'The Carnival is a floating pocket demiplane that appears throughout Ravenloft. As such, it can be used by travelers to navigate between Ravenloft''s demiplanes, as long as they aren''t picky about where they go.', 'Traveling Pocket'),
('Cavitus', 'Most of the domain is a desert which saps the life force of anyone who sets foot in it.', 'The Burning Peaks (Cluster)'),
('Darkon', 'Darkon is one of the few domains of Ravenloft to accept demihumans such as elves and dwarves as equal citizens, and one of the few to embrace arcane magic openly. Darkon is often considered decadent by its neighbors, appropriate enough as Azalin encourages his citizens to debase themselves as a means of salving his own ego.', 'The Northern Core'),
('Davion', 'Davion is a pocket domain ruled by a power-hungry and insane man called Davion the Mad, whose identity is shared with three other people. Each of these identities, one named Augustus, one of Loviatar called Narana, and the last named Boromar, becomes dominant over the others for a period of time, and the domain''s guise changes to suit the identity currently in command.
Davion can only be accessed through the Nightmare Lands. The portal to Davion there is one of many dreamspheres found throughout the domain.', 'Pocket'),
('Dementlieu', 'Modelled after Renaissance France, Dementlieu is led by the political puppet lord-governor Marcel Guignol, though the domain is truly ruled by the charismatic and manipulative Dominic D''Honaire. It is considered the cultural heart of the Core.', 'The Northern Core'),
('Dominia', 'Dominia is an island ruled by Dr. Dominiani (also known as Dr. Daclaud Heinfroth), an alienist and cerebral vampire who seeks to find a cure for madness by inflicting it on others, observing the effects and searching for treatments. The island is home to his renowned Asylum for the Mentally Disturbed. Before Dominia''s formation, Dr. Dominiani was an assistant to Duke Nharov Gundar of Gundarak. The Doctor was directly responsible for the Duke''s death, and temporarily held the position of Darklord of Gundarak until Barovia and Invidia moved to annex the territory.', 'Island'),
('Falkovnia', 'Falkovnia is ruled by Vlad Drakov, a mad tyrant (and former Krynnian mercenary) with a love of impaling as an execution method (an obvious reference to the Wallachian voivode, sometimes known as "Vlad the Impaler", although Drakov also shows echoes of Hitler and Stalin). Falkovnia produces much of the Core''s grain and wheat, which Drakov uses to fund his war machine. As absolute ruler of Falkovnia, everything is his property, including the population, which are branded with the mark of a hawk on their foreheads shortly after birth.', 'The Northern Core'),
('Forlorn', 'Forlorn is a tiny domain mainly inhabited by goblyns, monstrous slaves created by dark magic. A handful of humans live in the woods and underground, fighting the goblyns. The darklord is a cursed individual named Tristen ApBlanc, vampyre by day, ghost by night, who inhabits a castle caught in temporal flux due to the massive amounts of ethereal resonance created by the ghosts there. Those who enter Castle Tristenoira are subject to time travel to one of three time-lines, each fundamental to the creation of the domain. As such, Forlorn maintains no ties with any other domain and none of the other lords or lands pay it any heed.', 'The Southern Core'),
('Gundarak', 'Gundarak is a former core domain, originally ruled by Duke Gundar, and later by Dr. Daclaud Heinfroth. It was absorbed by Invidia and Barovia during the Grand Conjunction.', 'Former Core'),
('G''Henna', 'G''Henna is now an Island of Terror, but it was once part of the Core. G''Henna and Markovia were displaced from the Core during the Great Upheaval.', 'Island'),
('Har''Akir	', 'Har''Akir is the centre domain which makes up the Amber Wastes cluster, being merged together with Sebua and Pharazia. Har''Akir''s darklord is an mummy by the name of Ankhtepot, infamous amongst the natives for the cruel experiments into obtaining immortality he performed whilst he was alive.[1] The natives blame him for their current state, for their belief is that his actions angered the gods and led to the destablisation of Ma''at.Har''Akir is primarily a sandy desert, scattered with ancient ruins and a few oases. Har''Akir is also the domain featured in the 1995 computer game by SSI, Ravenloft: Stone Prophet. Har''Akir serves as the headquarters for the Green Hand.', 'The Amber Wastes (Cluster)/Island'),
('Hazlan', 'Hazlan is an exotic domain of ancient, eldritch secrets and powerful magic. It situated in the southern part of the Core, bordered by Kartakass to the west, Forlorn to the northwest, Nova Vaasa to the northeast and east, and the Misty Border to the south. The domain''s ruler and darklord is Hazlik, a member of the Red Wizards of Thay from the Forgotten Realms campaign setting. As a powerful practitioner of arcane magic, he presents the Church of the Lawgiver with an uneasy situation as the dominant Hazlani faith that should in theory condemn its practice. Though he banned its use until after the Grand Conjunction, Hazlan now encourages practice of arcane magic under his tutelage. Furthermore, the Mulan, the dominant ethnic group of Hazlan in power if not population, culturally embrace the use of arcane magic despite their faith in the Lawgiver. Hazlan is strictly ethnocratic in terms of power distribution, with the Mulan holding most of the power but only constituting less than ten percent of Hazlan''s population, with the oppressed Rashemani comprising the vast majority Hazlan''s population but also its lower classes. Despite the esoteric and complex system of exchanging favors, the intrigue and paranoia pervasive in Hazlani society put trust at a minimum among its people. Fortunately, internal squabbles and distrust of the outside keep Hazlani attention focused mostly inward.', 'Core'),
('The House of Lament', 'This small pocket domain is always found within another domain, and moves. It consists of a large old house with an attached stone tower. The tower was once part of a castle built by the sadistic Lord Dranzorg who would stop at nothing to prey on his neighbors, even to the point of entombing Mara, one of his neighbors'' daughters (who had been promised to him to end the endless pillaging), alive in its newly-built foundations. Her apparition eventually killed him and his men, however, and the castle - with the exception of the tower - fell into disrepair. The house was later added by a merchant, who, along with his family, fell victim to the haunt in the house. The darklord for the house is actually the house itself, which has fused with the spirit of Mara. Because Mara was entombed in it, she became intensely lonely. As a result, the house will not let any visitors leave until one of them sacrifices himself or herself to placate her unquenchable loneliness. The house will manifest its true nature gradually. First of all, neither doors nor windows will open, not even with magic; strange noises will begin to be heard. Then, the walls may begin to bleed, or messages such as "Mara is lonely" will appear in random places. If the walls are attacked, they bleed, too; if enough blood is shed, the house can form a the equivalent of a gray ooze or even a blood elemental with it.', 'Pocket'),
('I''Cath', 'I''Cath is a small domain ruled by Tsien Chiang, a powerful sorceress from Kara-Tur who hates all men.', 'Island'),
('Invidia', 'A land of passion torn by civil war and awash with the blood of ethnic strife, Invidia hangs on by a tenuous thread above the jaws of all-out chaos.[7] The fiendish tyrant Malocchio Aderre deposed the lackadaisical rule of his mother Gabrielle Aderre[4] and has begun to unite formerly independent settlements of Invidia into a single nation, though one that is firmly beneath his heel. Yet, as the much-feared Dukkar, he mainly seeks power to eradicate the Vistani and torment those around him.', 'The Southern Core'),
('Kalakeri', 'Called Sri Raji, the Steaming Lands, and various wild names by merchants coming from afar, Kalakeri[1] exists as a land of lush rainforests dotted with rivers and lakes. Long ruled by the Vasavadan dynasty, Kalakeri''s history of orderly rule and cosmopolitan exchange has been breached by the tide of civil war and corruption. Ramya Vasavadan, Kalakeri''s queen, laid a powerful curse upon the land as she perished in the assassination perpetrated by her siblings Arijani and Reeva. Now existing in an death knight following her undead restoration, she feuds with her siblings, transformed by her curse into monsters, for control over Kalakeri. Their conflict has rendered Kalakeri a pale reflection of its former heights of enlightenment and good fortunes, with its citizens always living at knife''s edge of death.', '(Cluster)'),
('Kalidnay	', 'Kalidnay is a domain taken from Athas (Dark Sun setting). It is ruled by the High Priestess Thakok-An[1], whose defining crime was the sacrifice of her family in order to transform her Sorcerer King, Kalid-Ma, into a dragon. Instead of transforming, the King was put into a deep sleep, and half of the city''s population was killed. As soon as this happened, Kalidnay was added to Ravenloft as an Island of Terror. Thakok''s curse is having her beloved master at her side, as she wanted, but in a sleeping state, thus never having his favor. Worse, dissonance eats at her soul, for she is in conflict over whether keeping him to herself is greater than having his favor.[2] And in the meantime, she must eternally walk a tightrope keeping the magical ecology that keeps Kalidnay together from falling apart.', 'Island'),
('Kartakass', 'Kartakass is the most musical domain in Ravenloft, and most native bards originate from or have been trained there. It lies in the south of the Core. A domain with lush forests, it contains only two major settlements: Skald and Harmonia. It is crisscrossed with the rivers that originate from the Musarde River, which flows in from Sithicus and disappears into Hazlan. The domain is bordered by Barovia in the north, Hazlan in the east, and Sithicus in the west. South of this domain lay the Mists. Wedged between Barovia and Kartakass lies Forlorn, a mostly empty domain.', 'The Southern Core'),
('Keening', 'Keening is the domain ruled by Tristessa. It was created during the Scourge of Arak.', 'The Northern Core'),
('Lamordia', 'Lamordia is the cold, modern, coastal domain ruled by Baron Vilhelm von Aubrecker and Adam.', 'The Northern Core'),
('Markovia', 'Markovia is an island situated in the Sea of Sorrows[1] and based on the H.G. Wells novel The Island of Doctor Moreau. The domain''s sole inhabitants are Dr. Frantisek Markov and his unique broken ones (tormented humanoids created by the fleshcrafting of animals with Markov''s perverse surgical methods). His obsession is the creation of humans from animals, a project doomed to ultimate failure. His creations are inhuman looking and degenerate slowly back into mere mindless beasts.', 'The Western Seas'),
('Mordent', 'Mordent is the setting of the module Ravenloft II: The House on Gryphon Hill. After one of Strahd and Azalin''s many attempts to escape the Demiplane of Dread, they found themselves in Mordent. After the events involving the Alchemist and the Apparatus, they were sent back, and Mordent was added to the demiplane as a new domain.', 'The Western Core'),
('Nebligtode', 'Formed in 635 BC, Nebligtode was a domain consisting of a number of islands floating in or reachable by the Sea of Sorrows and their surrounding waters. Graben Island, the most notable of the islands, along with Knammen Island and several smaller islets sat 75 miles away from the Lamordian coast.[4] The relatively bleak and barren island of Todstein lied 60 miles to the west of Graben. In 750 BC, Nebligtode was ripped from the Sea of Sorrows, and its islands joined the Nocturnal Sea on the opposite side of the Core.', 'The Eastern Seas'),
('Necropolis', 'Undead Haven', 'The Northern Core'),
('The Nightmare Lands', 'Originally a core domain located east of Nova Vaasa, since the Grand Conjunction The Nightmare Lands have become either a floating pocket domain or an Island of Terror located in the Mists. (See Pocket or Island?, below). The domain is ruled by the Nightmare Court, consisting of The Nightmare Man, Hypnos, Mullonga, The Ghost Dancer, Morpheus, and The Rainbow Serpent (with The Redheaded Child being a later addition to the court). The Nightmare Lands are composed of a landscape that is always shifting, reflecting its dreamlike nature, although it is often nightmarish. The only native inhabitants are the Abber Nomads, a band of primitive humans who are naturally immune to the many illusions this domain creates. The domain has a strong connection to the Plane of Dreams, and dreamers in any domain can find their dream selves drawn into a dreamscape in the Nightmare Lands.', 'Pocket'),
('Nosos', 'Nosos is a domain of over-industrialization, a land buried under garbage and poison. The darklord of the domain is Malus Sceleris, a human male. Nosos was an Island of Terror in the second edition version of Ravenloft, but was left out of the third edition version.', 'Island'),
('Nova Vaasa', 'Nova Vaasa was a Domain of Dread located in the farthest southeastern corner of the Core, bordering the Nocturnal Sea to the east.', 'The Southern Core'),
('Odiare', 'An Island of Terror, Odiare is made up of a single thorp or hamlet inhabited mostly by children. The overlord is a marionette named Maligno. This domain is based upon a twisted version of the traditional Italian children''s fable, Pinocchio by Carlo Collodi. Indeed, Odiare originated in Gothic Earth, and the language used is Italian.', 'Island'),
('Paridon', 'Loosely based on Victorian London, Paridon is a domain designed around the idea of social decay, one which happens to be infested with dread doppelgangers. The darklord is the doppelganger Sodo, and is referred to by the human inhabitants as ''Flickerflame'' because he cannot control his shape-changing powers and is constantly ''flickering'' in form. Previously an island of terror, Paridon and the domain of Timor (located within the sewers) form the Zherisia cluster.', 'Zherisia (Cluster)/Island'),
('Pharazia', 'Formerly an island of terror, Pharazia is a domain of the Amber Wastes, ruled by Diamabel. Like the rest of the Amber Wastes, the majority of Pharazia is unforgiving desert interrupted far too sporadically by oases that provide water to the realm''s mucky, crocodile infested rivers. Harsh like the scorching desert is Pharazian society, for it is governed by the austere, purity-obsessed laws of Diamabel enforced by his scourge-wielding confessors and the wrath of the Black Herald. Only the desert nomads led by Sheikh Allahn el Rashaan defy Diamabel, though they have stern customs and harsh punishment systems of their own.', 'The Amber Wastes (Cluster)'),
('Richemulot', 'A domain where life is centered around seemingly egalitarian, urban life, Richemulot is a nation based more on merit than material wealth. The citizens are able to leave mostly clean lives without fear of the overt oppression or abuse of other lands. Yet beneath this facade of opportunity and equality, corruption festers like a hidden tumor. From the sewers beneath the streets to the closed doors of the elite, wererats and other horrors eat at Richemulot in secret.', 'The Southern Core'),
('Scaena', 'Scaena is a travelling pocket domain consisting of a single theater. It is ruled by the mad playwright Lemot Sediam Juste, who has nearly unlimited power to create perfect illusions on the stage.', 'Pocket'),
('The Nocturnal Sea', 'The Nocturnal Sea', 'The Nocturnal Sea'),
('The Sea of Sorrows', 'The Sea of Sorrows is the sea that borders the western mainland of the Core. Although the sea itself was formed in 630 BC, it may not have gained a darklord until 740 BC in the wake of the Grand Conjunction. Like with the Nocturnal Sea, the Sea of Sorrows boasts several islands. Some of these islands have human populations on them, but the presence of fog makes the Sea difficult to charter, even by its darklord. Towards its edge, the Sea gives way entirely to the Misty Border. In addition, many of the islands located within the interior of the Sea are either hostile to outside trade or have limited capacity for it. Lands beyond may be reached via the Sea of Sorrows, but such routes are the most precarious. Sailors of the Core''s western shorelines may wishfully speak of a way to sail through and around to the Nocturnal Sea and its more plentiful ports, but there is scant evidence that the possibility even exists.', 'The Western Seas'),
('The Shadow Rift', 'The Shadow Rift', 'The Shadow Rift'),
('Sebua', 'Originally an Island of terror, Sebua is a domain of the Amber Wastes, ruled by Tiyet. It is a harsh desert land. Hidden beneath and within the ruins, sandy dunes, and desolate rocky flats lies the wealth and secrets of a lost Bronze Age civilization resembling that of Har''Akir, though the only living Sebuan native people of any numbers are children that live in Stone Age living conditions. These "wild children" dwell within the ruined city of Anhalla. Oases in the wastelands are surprisingly not uncommon, though pollution or hidden dangers often befoul them. Although the land bears natural resources, the Pharazian nomads that travel through Sebua to reach the neighboring domain of Har''Akir do not for the most part linger long to exploit them, for Sebua is considered a vile and unholy land.', 'The Amber Wastes (Cluster)'),
('Sithicus', 'Sithicus, meaning The Land Of Specters in the Elven tongue, is unusual in being one of the few domains inhabited primarily by non-humans, in this case elves. Created and formerly ruled by the Death Knight Lord Soth before his disappearance, Sithicus is now officially the kingdom of the werebadger Azrael Dak, who is far more interested in the fates of his subjects than Soth was. Other than elves, the sentient races inhabiting Sithicus include a few small pockets of humans, and several tribes of tortured, tormented Vampire kender, who are usually mistaken for [halflings?]. The Darklord of Sithicus is a half-Vistani/half-shadow woman by the name of Inza Kulchevich, daughter of Magda Ilyanova Kulchevich.', 'The Southern Core'),
('Souragne', 'Souragne is a domain based around stereotypical Louisiana voodoo, and as such consists primarily of a vast swamp. The two most important individuals in Souragne are the darklord Anton Misroi, a zombie lord, and Chicken Bone, the most powerful voodan (Ravenloft''s equivalent of a houngan) in the swamp.', 'Island'),
('Sri Raji', 'formerly an island of terror, Sri Raji is a domain in the Verduous Lands cluster ruled by the Maharaja Arijani. The Verduous Lands cluster does not have a moon with potentially interesting consequences for lycanthropes having some part of the lunar cycle as their trigger condition. Equally, there should be no tides.', 'Island'),
('Tepest', 'Tepest is a rural and heavily forested domain with a fairy tale like quality to it. Although the land is infested with many dangers- malevolent goblins and insidious hags- it is the beguiling and manipulative influence of the fey that bothers the Tepestani the most. Ever since the Grand Conjunction of 740 BC that resulted in the Shadow Rift eating up several neighboring lands, the Tepestani Inquisition has served to root out the fey and their agents. Unfortunately, the Inquisition is not terribly discrete in how it defines their targets- such as elves, gnomes, sorcerers- are all prime targets for being hunted. As with any witch hunt, sometimes entirely innocent targets find undeserved fates. Such false accusations have caused Wyan of Viktal, the Inquisition''s founder, to put serious limits on the growth of the Inquisition''s reach. However, the resurgence of the Inquisition''s popularity and power may have resulted in a movement behind his ability to control.', 'The Northern Core'),
('Timor', 'Formerly an island of terror, Timor is now part of the Zherisia cluster, consisting of the sewer and underground beneath Paridon. It is ruled by The Hive Queen, although by some accounts she is not the domain''s first darklord. This dread realm is not one populated humans but instead is dominated by the savage and elusive aberrations known as the marikith.', 'The Northern Core'),
('Tovag', 'Medival', 'The Burning Peaks (Cluster)'),
('Valachan', 'The chilly, heavily forested lands of Valachan sits in the southwest most part of the Core. This domain is home to the Valachani, an industrious and self-sufficiency-minded people. The people speak of the forest''s denizens in myth and legend, with the panther as the most admired yet the most feared. Life inside of the communities is generally calm. However, the people are terrorized by the enforcers of Baron Urik von Kharkov and their leader, Lady Adeline.', 'The Southern Core'),
('Vechor', 'Vechor an ever-changing domain is ruled by Easan the Mad.', 'The Nocturnal Sea'),
('Verbrek', 'Verbrek is a land of rugged forests and scattered settlements. In this wild and woolly domain, it is not the human that dominates but rather the wolf. More specifically, the werewolf, as werewolves both outnumber and out-power the humans of Verbrek. The Verbrekers can''t even completely trust their own, as the sheepskinner werewolves dons the guise of humanity and live in seemingly normal communities.', 'The Southern Core'),
('Vorostokov', 'Vorostokov is the domain ruled by Gregor Zolnik, originally an Island of Terror, now part of the Frozen Reaches.', 'Island/Frozen Reaches');





-- people
INSERT INTO people(name, race, description, domain_id) VALUES
('Count Strahd von Zarovich','Vampire', 'The Vampire darklord of Barovia. He rules the land publicly from Castle Ravenloft as Strahd XI, supposedly a descendant of Strahd I, but actually the same man. Strahd murdered his younger brother Sergei von Zarovich on his wedding day in an attempt to claim Sergi''s bride, Tatyana Federovna. This is the final act that caused him to become the first known darklord. Tatyana rejected his love and jumped to her death from the walls of Castle Ravenloft. Strahd is now cursed to hunt and lose the reincarnations of Tatyana.', (SELECT domain_id FROM domains WHERE domain_name = 'Barovia'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Lady Ivana Boritsi','Human', 'Ivana Boritsi 689-present) is the co-darklord of Borca with her cousin, Ivan Dilisnya (the former darklord of Dorvinia. Prior to the Grand Conjunction and the merging of their domains, Lady Ivana was the sole darklord of Borca. However, Ivana was not the first darklord of Borca; she claimed the title from her mother, Camille Boritsi, after securing her death with poison.', (SELECT domain_id FROM domains WHERE domain_name = 'Borca'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Ivan Dilisnya','Human', 'Ivan Dilisnya (689-present) is the co-darklord of Borca with his cousin, Ivana Boritsi. Prior to the Grand Conjunction and the merging of their domains, Ivan was the darklord of Dorvinia. He was granted his darklordship when he fled into the Mists some time after poisoning his sister and her husband, and attempting to kill their newborn child. Formerly flamboyant and a lover of the finer things in life, his personal curse is the loss of his sense of taste, leaving him murderously frustrated when others around him enjoy what he cannot anymore.', (SELECT domain_id FROM domains WHERE domain_name = 'Borca'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Azalin Rex','Lich', 'As a lich, an undead wizard, Azalin''s true appearance resembles a skeleton or mummy. In his everyday appearance, however, Azalin maintains the illusion of a living king, closely mimicking his late-life persona: an elderly man with aquiline features and a piercing gaze, with unkempt dark hair topped by a heavy iron crown. However, he can alter his appearance to resemble many humanoid individuals, even that of a different race or gender.', (SELECT domain_id FROM domains WHERE domain_name = 'Darkon'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Dominic d''Honaire','Human', 'Dominic d''Honaire is the darklord of Dementlieu. He is not its temporal leader but does serve as an adviser for Marcel Guignol. He sits on the Council of Brilliance but he does not head it. However, Dominic''s has much more power than his official position would suggest. The darklord''s power is domination of the mind of other people on a prodigious scale. A great many in the land, including its recognized head, are his obedients and through this network he knows whatever goes on in his land. Like all darklords, Dominic is not without a curse. His personal curse is that any woman he woos sees him as more repulsive the more he is attracted to her. Also, for some time his rule is challenged by an entity who is called (and virtually is) the Living Brain, the last remains of Rudolph von Aubrecker, the youngest son of Lamordia''s political ruler.', (SELECT domain_id FROM domains WHERE domain_name = 'Dementlieu'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Vlad Drakov','Human', 'Vlad Drakov is the darklord of Falkovnia, although the extent to which he appreciates this fact, and in particular his curse, is unclear. Drakov originally came from the country of Thenol on the continent of Taladas in Krynn, where he was a mercenary captain known as the Hawk. His men were the Talons of the Hawk, and they were widely known as cruel and callous enforcers selling their talents to the highest bidders, no questions asked. When Drakov first arrived in the Land of Mists, he and his men found themselves in Darkon, where they set about trying to make a territorial claim by destroying a village and putting the inhabitants on pikes. When the villagers animated as the walking dead, Drakov and his men were forced to flee into the Mists. There the domain of Falkovnia was revealed to Drakov and held him fast.', (SELECT domain_id FROM domains WHERE domain_name = 'Falkovnia'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Tristen ApBlanc','Vampyre/Ghost', 'Tristen ApBlanc was the Darklord of Forlorn. He is cursed to live as a vampyre during the day and a ghost during the night.[1][2]
After murdering the druid Rual who raised him, he committed many crimes over hundreds of years known as the Time of Terrors. The unjust execution of the last of the ApFittle family was the seminal event that formed Forlorn.', (SELECT domain_id FROM domains WHERE domain_name = 'Forlorn'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Hazlik','Human', 'Hazlik had bald head, covered with ornate tattoos, and a brown goatee. His left eye was brown, while his right eye was blue. He tended to wear long red robes that exposed his hairless, tattooed chest. His voice was noted as being phlegmy and like a hiss.', (SELECT domain_id FROM domains WHERE domain_name = 'Hazlan'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Gabrielle Aderre','Human', 'Born in the approximate year of 710 BC, Gabrielle Aderre is the darklord of Invidia, though her rule over her domain is severely challenged by her son Malocchio Aderre, whom she conceived with the Gentleman Caller as the father. Malocchio is widely considered to be the prophesied Dukkar who will bring about the destruction of the Vistani.', (SELECT domain_id FROM domains WHERE domain_name = 'Invidia'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Adam','Dread Flesh Golem', 'Adam is the darklord of Lamordia. Known as Mordenheim''s Monster or the Creature, he is an extremely intelligent and nimble dread flesh golem, based on Mary Shelley''s Frankenstein. Adam is the most successful creation of Dr. Victor Mordenheim in his research into the creation of life, albeit the one that causes him grief unmeasured. Adam reduced the doctor''s wife Elise to a vegative state and apparently murdered their adopted daughter Eva.', (SELECT domain_id FROM domains WHERE domain_name = 'Lamordia'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Wilfred Godefroy','Human', 'A cruel and brutal aristocrat who murdered his wife Estelle Weathermay and daughter Lilia Godefroy, and then framed the act as an accident. He endured a year of their ghostly vengeance before committing suicide, but this did not end his torment for long. After Mordent was pulled into the Demiplane of Dread and the Alchemist met his apparent end, Azalin and Strahd soon withdrew from the domain. This left Lord Wilfred as the greatest evil within Mordent. After he became ghostly darklord of Mordent, their ghosts of his wife and daughter rose quickly to torment him once again. They repeat this pattern every night to haunt and consume him eternally.', (SELECT domain_id FROM domains WHERE domain_name = 'Mordent'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Death (Lowellyn Dachine)','Negative Energy Elemental', 'Death is the darklord of Necropolis and leads the Unholy Order of the Grave. This creature was formerly Lowellyn Dachine, a Kargat who was in fact both a clone and a prodigy of Azalin Rex. Lowellyn was transformed into a negative energy elemental by the Infernal Machine in the events leading up to the Requiem. He now considers himself to be the true incarnation of Death itself. Death lairs in Grim Fastness in the Old Il Aluk part of the Aluk Meridian borough of Il Aluk.', (SELECT domain_id FROM domains WHERE domain_name = 'Necropolis'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Meredoth','Human', 'Meredoth was the darklord of an Island of Terror domain called Nebligtode. This domain was actually a large body of water with several islands within it. The most notable of these islands were Todstein and Graben Island. Meredoth festered like this in Ravenloft for over a century before the Grand Conjunction happened. The Dark Powers have diminished his aging to to but a snail''s pace, but the years are still creeping up on him.', (SELECT domain_id FROM domains WHERE domain_name = 'The Nocturnal Sea'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Malken','Human', 'Malken is the alter-ego of Sir Tristen Hiregaard and is the darklord of Nova Vaasa. Because of the dual personality, he can only access his darklord abilities when Sir Hiregaard is not in control of their shared body. Likewise, because of their dual-nature, Malken is unable to close the borders of his domain.', (SELECT domain_id FROM domains WHERE domain_name = 'Nova Vaasa'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Jacqueline Renier','Wererat', 'A scion of the wererat branch of the Renier family, Jacqueline became darklord of Richemulot after murdering her grandfather Claude Renier. Jacqueline is the child of Claude''s daughter Marie and the human nobleman Simon Audaire (Marie killed her husband and gave her children her maiden name, a family tradition in which Jacqueline has followed suit). Jacqueline resides in Chateau Delanuit with her twin sister Louise.', (SELECT domain_id FROM domains WHERE domain_name = 'Richemulot'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Captain Pieter Van Riese','Ghost', 'Pieter van Riese was, and remains, a ship''s captain. Captain van Riese had an obsession with discovering a path from his homeland to through the treacherously icy waters of the north to the exotic far east. Driving his ship, the Relentless, through storm and sea, he would not relent to his crew''s calls to turn back. But as the storm reached its peak, the Relentless was at last undone. At his lowest moment, Captain van Riese cried out with the offer of his life plus all of his crew, to any being able to push them forward. His wishes were granted, though not as he''d hoped. Captain van Riese survived his death as a ghost, becoming also the darklord of the Sea of Sorrows.', (SELECT domain_id FROM domains WHERE domain_name = 'The Sea of Sorrows'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Gwydion the Sorcerer','Fiend', 'Gwydion the Sorcerer-Fiend was the Darklord of Arak. In 740 BC as part of the Great Upheaval, Niurin Scaa, the kindgom of shadow fey hidden beneath the surface of Arak, was dragged away to the southwest by Gwydion. The land of Arak ceased to be and the Land of the Mists tore open beyond Tepest. The Shadow Rift, sealed by roiling black mist, was the new land of the Arak with Gwydion as is Darklord.', (SELECT domain_id FROM domains WHERE domain_name = 'The Shadow Rift'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Inza Kulchevich','Vistani', 'Introduced in the novel Spectre of the Black Rose, Inza Magdova Kulchevich is the current darklord of Sithicus, replacing Lord Soth. She is a Vistana, the daughter of Magda Kulchevich[3], the great granddaughter of Madame Girani, and a descendant of the legendary vistana Kulchek the Wanderer. She wields his potent magic dagger Novgor, with which sabotaged her mother''s cudgel Gard and precipitated her death.', (SELECT domain_id FROM domains WHERE domain_name = 'Sithicus'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Laveeda','Hag', 'The Three Hags of Tepest, also referred to as the Sisters Mindefisk, are the collective co-Darklords of Tepest. All three were once seemingly normal human sisters raised as part of the Mindefisk family, albeit not born into the family but rather given to the mother by the fey because of her unfulfilled desire for daughters. Their individual names are Laveeda, Leticia and Lorinda', (SELECT domain_id FROM domains WHERE domain_name = 'Tepest'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Leticia','Hag', 'The Three Hags of Tepest, also referred to as the Sisters Mindefisk, are the collective co-Darklords of Tepest. All three were once seemingly normal human sisters raised as part of the Mindefisk family, albeit not born into the family but rather given to the mother by the fey because of her unfulfilled desire for daughters. Their individual names are Laveeda, Leticia and Lorinda', (SELECT domain_id FROM domains WHERE domain_name = 'Tepest'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Lorinda','Hag', 'The Three Hags of Tepest, also referred to as the Sisters Mindefisk, are the collective co-Darklords of Tepest. All three were once seemingly normal human sisters raised as part of the Mindefisk family, albeit not born into the family but rather given to the mother by the fey because of her unfulfilled desire for daughters. Their individual names are Laveeda, Leticia and Lorinda', (SELECT domain_id FROM domains WHERE domain_name = 'Tepest'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Urik von Kharkov','Vampire', 'Urik von Kharkov is Darklord of Valachan. He has an unusual and complicated backstory, as a panther who was polymorphed into human form Morphayus, a Red Wizard of Thay to use as a sleeper agent against his rival Selena. Having forgotten his animal self, Kharkov was sent by Morphayus to Cormyr to receive an education unknowingly in preparation for use against Selena. Introduced to her as a fine nobleman and baron, von Kharkov soon fell in love with Selena, and she returned his feelings. When Selena was most vulnerable, Morphayus removed his enchantment and causing Von Kharkov, now again a panther, to tear his lover to shreds. Morphayus transformed Von Kharkov back into human once more. Horrified at what had happened and afraid to be used as a tool a second time, he fled and was taken by the Mists into Ravenloft, emerging in the realm of Darkon.', (SELECT domain_id FROM domains WHERE domain_name = 'Valachan'));
INSERT INTO people(name, race, description, domain_id) VALUES
('Alfred Timothy','Werewolf', 'Alfred Timothy is the darklord of the Core domain of Verbrek. In the wake of the Grand Conjunction, he also acquired the lands formerly belonging to the vanished realm of Arkandale. This was principally due to his father''s apathetic rule of that domain. Like his father, he is a true werewolf. He he is also a cleric, leading the Cult of the Wolf God.', (SELECT domain_id FROM domains WHERE domain_name = 'Verbrek'));


-- domain_events
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'First domain'),(SELECT domain_id FROM domains WHERE domain_name = 'Barovia'));
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'Duncan MacFarn''s death'),(SELECT domain_id FROM domains WHERE domain_name = 'Barovia'));
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'Tristen kills Gilan'),(SELECT domain_id FROM domains WHERE domain_name = 'Forlorn'));
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'Strahd Diary'),(SELECT domain_id FROM domains WHERE domain_name = 'Barovia'));
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'Tristen kills Morholt'),(SELECT domain_id FROM domains WHERE domain_name = 'Forlorn'));
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'First Dead Mans War'),(SELECT domain_id FROM domains WHERE domain_name = 'Darkon'));
INSERT INTO domain_events(event_id, domain_id) VALUES((SELECT event_id FROM events WHERE event_name = 'First Dead Mans War'),(SELECT domain_id FROM domains WHERE domain_name = 'Falkovnia'));

-- event_people
INSERT INTO event_people(event_id, person_id) VALUES((SELECT event_id FROM events WHERE event_name = 'First domain'),(SELECT person_id FROM people WHERE name = 'Count Strahd von Zarovich'));
INSERT INTO event_people(event_id, person_id) VALUES((SELECT event_id FROM events WHERE event_name = 'Strahd Diary'),(SELECT person_id FROM people WHERE name = 'Count Strahd von Zarovich'));
INSERT INTO event_people(event_id, person_id) VALUES((SELECT event_id FROM events WHERE event_name = 'Tristen kills Morholt'),(SELECT person_id FROM people WHERE name = 'Tristen ApBlanc'));
INSERT INTO event_people(event_id, person_id) VALUES((SELECT event_id FROM events WHERE event_name = 'First Dead Mans War'),(SELECT person_id FROM people WHERE name = 'Vlad Drakov'));
INSERT INTO event_people(event_id, person_id) VALUES((SELECT event_id FROM events WHERE event_name = 'First Dead Mans War'),(SELECT person_id FROM people WHERE name = 'Azalin Rex'));



-- domain_lords
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Count Strahd von Zarovich'), (SELECT domain_id FROM domains WHERE domain_name = 'Barovia'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Lady Ivana Boritsi'), (SELECT domain_id FROM domains WHERE domain_name = 'Borca'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Ivan Dilisnya'), (SELECT domain_id FROM domains WHERE domain_name = 'Borca'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Azalin Rex'), (SELECT domain_id FROM domains WHERE domain_name = 'Darkon'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Dominic d''Honaire'), (SELECT domain_id FROM domains WHERE domain_name = 'Dementlieu'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Vlad Drakov'), (SELECT domain_id FROM domains WHERE domain_name = 'Falkovnia'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Tristen ApBlanc'), (SELECT domain_id FROM domains WHERE domain_name = 'Forlorn'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Hazlik'), (SELECT domain_id FROM domains WHERE domain_name = 'Hazlan'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Gabrielle Aderre'), (SELECT domain_id FROM domains WHERE domain_name = 'Invidia'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Adam'), (SELECT domain_id FROM domains WHERE domain_name = 'Lamordia'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Wilfred Godefroy'), (SELECT domain_id FROM domains WHERE domain_name = 'Mordent'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Death (Lowellyn Dachine)'), (SELECT domain_id FROM domains WHERE domain_name = 'Necropolis'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Meredoth'), (SELECT domain_id FROM domains WHERE domain_name = 'The Nocturnal Sea'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Malken'), (SELECT domain_id FROM domains WHERE domain_name = 'Nova Vaasa'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Jacqueline Renier'), (SELECT domain_id FROM domains WHERE domain_name = 'Richemulot'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Captain Pieter Van Riese'), (SELECT domain_id FROM domains WHERE domain_name = 'The Sea of Sorrows'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Gwydion the Sorcerer'), (SELECT domain_id FROM domains WHERE domain_name = 'The Shadow Rift'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Inza Kulchevich'), (SELECT domain_id FROM domains WHERE domain_name = 'Sithicus'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Laveeda'), (SELECT domain_id FROM domains WHERE domain_name = 'Tepest'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Leticia'), (SELECT domain_id FROM domains WHERE domain_name = 'Tepest'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Lorinda'), (SELECT domain_id FROM domains WHERE domain_name = 'Tepest'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Urik von Kharkov'), (SELECT domain_id FROM domains WHERE domain_name = 'Valachan'));
INSERT INTO domain_lords(person_id, domain_id) VALUES
((SELECT person_id FROM people WHERE name = 'Alfred Timothy'), (SELECT domain_id FROM domains WHERE domain_name = 'Verbrek'));

